### ISSUE TITLE
Add support for DROP PROCEDURE

### ISSUE THREAD

**Issue by FredYakumo** [sqlparser-rs/sqlparser-rs#1282]
https://github.com/sqlparser-rs/sqlparser-rs/blob/9d15f7e9a92a4ef36fcc6d3166fd0221a22a20e2/src/parser/mod.rs#L4217
drop procedure stmt is allowed in many sql client impl.
(https://dev.mysql.com/doc/refman/8.0/en/drop-procedure.html,
https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-procedure-transact-sql?view=sql-server-ver16,
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/DROP-PROCEDURE.html,
...)

**Comment by LorrensP-2158466** [comment]
I would like to take on this issue.
If i remember correctly, `DROP PROCEDURE ...` is part of the SQL spec, so we can just implement it in the Parser crate, right?

I would implement this in the same way as `parse_drop_function` and also add a new Statement called `DropProcedure`.
https://github.com/sqlparser-rs/sqlparser-rs/blob/9d15f7e9a92a4ef36fcc6d3166fd0221a22a20e2/src/parser/mod.rs#L4250-L4267

But i did notice that the syntax for both are the same, the only difference is `PROCEDURE` instead of `FUNCTION`.
I can maybe combine these two?
