### ISSUE TITLE
distinguishing between `Int` and `Integer`

### ISSUE THREAD

**Issue by tvallotton** [sqlparser-rs/sqlparser-rs#398]
Currently the parser will parse `INT` and `INTEGER` into the same AST representation. It will later serialize it back all into `INT`. Unfortunatly, in SQLite `INT` is not recognized as a valid type. This means that primary keys with `INT` as a type do not enforce type checking nor do they support autoincrementing functionality. 
Thus, parsing this file and displaying it back again would introduce a runtime error: 
```sql
CREATE TABLE foo (
   bar INTEGER NOT NULL PRIMARY KEY,
   baz TEXT
); 
INSERT INTO foo (baz) values ('baz'); 
```
I forked the project when I stumbled into this issue (I addressed it by defaulting to `INTEGER` instead of `INT`), but I still wanted to mention it in case you weren't aware of this.

**Comment by alamb** [comment]
Thanks @tvallotton  -- please feel free to submit a patch to correct it

**Comment by frolovdev** [comment]
I guess I can help

@alamb good day, and how the patch actually should look like? We should have different logic of serialization for MYSQL? Or do you mean something else

**Comment by alamb** [comment]
Hi @frolovdev  -- thank you 

I think the basic philosophy of this crate is that the parsed AST mirrors the SQL and users of the crate can handle it appropriately to their usecase. 

In this case I would recommend adding a `DataType::Integer` to the existing enum `DataType::Int` https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/ast/data_type.rs#L57 so that `x INT` and `x INTEGER` parse to different SQLParser DataTypes
