### ISSUE TITLE
PostgreSQL RETURNING Data From Modified Rows

### ISSUE THREAD

**Issue by Jekshmek** [sqlparser-rs/sqlparser-rs#60]
Postgresql [RETURNING](https://www.postgresql.org/docs/9.5/dml-returning.html)

```sql
INSERT INTO users (firstname, lastname) VALUES ('Joe', 'Cool') RETURNING id;

UPDATE products SET price = price * 1.10
  WHERE price <= 99.99
  RETURNING name, price AS new_price;

DELETE FROM products
  WHERE obsoletion_date = 'today'
  RETURNING *;
```
```rust
Err(ParserError("Expected end of statement, found: RETURNING"))
```

**Comment by nickolay** [comment]
_This seems to be truly Postgres-specific; an optional last clause of [INSERT](https://www.postgresql.org/docs/11/sql-insert.html), [DELETE](https://www.postgresql.org/docs/11/sql-delete.html), or [UPDATE](https://www.postgresql.org/docs/11/sql-update.html). Of these we currently implement only INSERT..VALUES and DELETE._

Adding this for INSERT..VALUES and DELETE should be easy: you can reuse `parse_select_list` and add the result to `SQLStatement::SQLInsert` and `SQLDelete`: `{ ..., returning: Vec<SQLSelectItem> }`.

@andygrove mentioned that it's fine to add dialect-specific constructs to the main parser until a better solution emerges, so I think a PR with tests would be accepted.

The INSERT .. SELECT .. RETURNING will require larger changes, as the keyword "RETURNING" is [reserved](https://www.postgresql.org/docs/11/sql-keywords-appendix.html) in Postgres - can't be used as a table/column name - so that in `INSERT INTO foo SELECT * FROM bar RETURNING id` "RETURNING" is recognized as a keyword and not as a table alias. We [have](https://github.com/andygrove/sqlparser-rs/commit/06fe053e59685c0983d92c34b6468602c0f6230d) `RESERVED_FOR_TABLE_ALIAS` / `RESERVED_FOR_COLUMN_ALIAS` to support that, but they're not dialect-specific at the moment.

The least fun part is that Postgres allows INSERT/UPDATE/DELETE to be used in place of SELECT, as in this example from their documentation:
```
WITH upd AS (
  UPDATE employees SET sales_count = sales_count + 1 WHERE id =
    (SELECT sales_person FROM accounts WHERE name = 'Acme Corporation')
    RETURNING *
)
INSERT INTO employees_log SELECT *, current_timestamp FROM upd;
```
We could follow [Postgres' lead](https://github.com/postgres/postgres/blob/bdf595adbca195fa54a909c74a5233ebc30641a1/src/backend/parser/gram.y#L10736) and change the `Cte`'s member from `SQLQuery` to a new enum for INSERT/DELETE/UPDATE as well as SELECT statements. But this feels like something that really ought to be specific to Postgres dialect...

**Comment by teenjuna** [comment]
Hello there! Is this still being considered? 😅
